#!/bin/sh /etc/rc.common

START=99
STOP=04

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-0}
    procd_set_param stderr 1
    procd_set_param command /root/bin/rpchatd
    procd_close_instance
}
